### ISSUE TITLE
Heroku does not work anymore

### ISSUE THREAD

**Issue by singhenso** [Loanify/Loanify#48]
Heroku crashed and I cannot do anything. Here is a screenshot.
<img width="800" alt="screen shot 2016-05-05 at 9 27 41 am" src="https://cloud.githubusercontent.com/assets/6751448/15049559/bb6b1bf2-12a3-11e6-8b99-a03259afff54.png">

**Comment by smLocal** [comment]
What steps did you take to get to this error?

**Comment by smLocal** [comment]
Issue fixed
