### ISSUE TITLE
app crashes 

### ISSUE THREAD

**Issue by ilya0** [Loanify/Loanify#49]
_Bug_
## Current Behavior

App crashes from the initialize
## Desired Behavior

App should open and run
## Steps to Replicate
1. open app
2. register new account on app
3. go to new equipment to register new equipment
4. form filled out
5. on submit - app crashes
## OS/Browser

ios mavericks
## Relevant Screenshots
- Attach any screenshots or pictures to help explain the problem

**Comment by smLocal** [comment]
The heroku site is working. Thank you for your concern.
